const foods = [
  {
    id: "1",
    name: "Meat Pizza",
    ingredients: "Mixed Pizza",
    price: "150",
    image: require("../assets/meatPizza.png"),
    quantity: 0,
  },
  {
    id: "2",
    name: "Cheese Pizza",
    ingredients: "Cheese Pizza",
    price: "120",
    image: require("../assets/cheesePizza.png"),
    quantity: 0,
  },
  {
    id: "3",
    name: "Chicken Burger",
    ingredients: "Fried Chicken",
    price: "80",
    image: require("../assets/chickenBurger.png"),
    quantity: 0,
  },
  {
    id: "4",
    name: "Sushi Makizushi",
    ingredients: "Salmon Meat",
    price: "80",
    image: require("../assets/sushiMakizushi.png"),
    quantity: 0,
  },
  {
    id: "5",
    name: "Idali",
    ingredients: "Salmon Meat",
    price: "90",
    image: require("../assets/idli.jpg"),
    quantity: 0,
  },
  {
    id: "6",
    name: "Dhossa",
    ingredients: "Salmon Meat",
    price: "120",
    image: require("../assets/dhossa.jpg"),
    quantity: 0,
  },
  {
    id: "7",
    name: "Uttapam",
    ingredients: "Salmon Meat",
    price: "80",
    image: require("../assets/uttapam.jpg"),
    quantity: 0,
  },
  {
    id: "8",
    name: "Pav Bhaji",
    ingredients: "Salmon Meat",
    price: "90",
    image: require("../assets/pavbhaji.jpg"),
    quantity: 0,
  },
  {
    id: "9",
    name: "Manchurian",
    ingredients: "Salmon Meat",
    price: "90",
    image: require("../assets/manchurian.jpg"),
    quantity: 0,
  },
  {
    id: "10",
    name: "Sandwich",
    ingredients: "Salmon Meat",
    price: "50",
    image: require("../assets/sandwich.png"),
    quantity: 0,
  },
  {
    id: "11",
    name: "Puff",
    ingredients: "Salmon Meat",
    price: "50",
    image: require("../assets/puff.jpg"),
    quantity: 0,
  },
  {
    id: "12",
    name: "Vadapav",
    ingredients: "Salmon Meat",
    price: "50",
    image: require("../assets/vadapav.jpg"),
    quantity: 0,
  },
];

export default foods;
